version: '3.8'

services:
  postgres:
    image: postgres:9
    ports:
      - 5432:5432
    environment:
      - TZ=Australia/Hobart
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=@DevelopmentPassword123
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups

volumes:
  postgres:
  postgres_backups:
