CREATE TABLE RegionSolution(
     id bigint NOT NULL PRIMARY KEY,
     run_time date,
     interval date,
     region smallint,
     rrp double precision,
     rop double precision,
     excess_generation double precision,
     raise_6_sec_rrp double precision,
     raise_6_sec_rop double precision,
     raise_60_sec_rrp double precision,
     raise_60_sec_rop double precision,
     raise_5_min_rrp double precision,
     raise_5_min_rop double precision,
     raise_reg_rrp double precision,
     raise_reg_rop double precision,
     lower_6_sec_rrp double precision,
     lower_6_sec_rop double precision,
     lower_60_sec_rrp double precision,
     lower_60_sec_rop double precision,
     lower_5_min_rrp double precision,
     lower_5_min_rop double precision,
     lower_reg_rrp double precision,
     lower_reg_rop double precision,
     total_demand double precision,
     available_generation double precision,
     available_load double precision,
     demand_forecast double precision,
     dispatchable_generation double precision,
     dispatchable_load double precision,
     net_interchange double precision,
     lower_5_min_dispatch double precision,
     lower_5_min_import double precision,
     lower_5_min_local_dispatch double precision,
     lower_5_min_local_req double precision,
     lower_5_min_req double precision,
     lower_60_sec_dispatch double precision,
     lower_60_sec_import double precision,
     lower_60_sec_local_dispatch double precision,
     lower_60_sec_local_req double precision,
     lower_60_sec_req double precision,
     lower_6_sec_dispatch double precision,
     lower_6_sec_import double precision,
     lower_6_sec_local_dispatch double precision,
     lower_6_sec_local_req double precision,
     lower_6_sec_req double precision,
     raise_5_min_dispatch double precision,
     raise_5_min_import double precision,
     raise_5_min_local_dispatch double precision,
     raise_5_min_local_req double precision,
     raise_5_min_req double precision,
     raise_60_sec_dispatch double precision,
     raise_60_sec_import double precision,
     raise_60_sec_local_dispatch double precision,
     raise_60_sec_local_req double precision,
     raise_60_sec_req double precision,
     raise_6_sec_dispatch double precision,
     raise_6_sec_import double precision,
     raise_6_sec_local_dispatch double precision,
     raise_6_sec_local_req double precision,
     raise_6_sec_req double precision,
     aggregate_dispatch_error double precision,
     initial_supply double precision,
     cleared_supply double precision,
     lower_reg_import double precision,
     lower_reg_dispatch double precision,
     lower_reg_local_dispatch double precision,
     lower_reg_local_req double precision,
     lower_reg_req double precision,
     raise_reg_import double precision,
     raise_reg_dispatch double precision,
     raise_reg_local_dispatch double precision,
     raise_reg_local_req double precision,
     raise_reg_req double precision,
     raise_5_min_local_violation double precision,
     raise_reg_local_violation double precision,
     raise_60_sec_local_violation double precision,
     raise_6_sec_local_violation double precision,
     lower_5_min_local_violation double precision,
     lower_reg_local_violation double precision,
     lower_60_sec_local_violation double precision,
     lower_6_sec_local_violation double precision,
     raise_5_min_violation double precision,
     raise_reg_violation double precision,
     raise_60_sec_violation double precision,
     raise_6_sec_violation double precision,
     lower_5_min_violation double precision,
     lower_reg_violation double precision,
     lower_60_sec_violation double precision,
     lower_6_sec_violation double precision,
     last_changed date,
     total_intermittent_generation double precision,
     demand_and_non_schedgen double precision,
     uigf double precision,
     semi_schedule_cleared_mw double precision,
     semi_schedule_compliance_mw double precision,
     ss_solar_uigf double precision,
     ss_wind_uigf double precision,
     ss_solar_cleared_mw double precision,
     ss_wind_cleared_mw double precision,
     ss_solar_compliance_mw double precision,
     ss_wind_compliance_mw double precision,
     wdr_initial_mw double precision,
     wdr_available double precision,
     wdr_dispatched double precision
);

CREATE INDEX IX_RegionSolution_interval ON RegionSolution (interval);
CREATE INDEX IX_RegionSolution_run_time ON RegionSolution (run_time);
CREATE INDEX IX_RegionSolution_region ON RegionSolution (region);
CREATE INDEX IX_RegionSolution_last_changed ON RegionSolution (last_changed);