CREATE TABLE Participants(
 id bigserial NOT NULL PRIMARY KEY,
 name text,
 abn varchar(128),
 demand_response_service_provider_ancillary_service_load bool DEFAULT FALSE,
 demand_response_service_provider_wholesale_demand_response_unit bool DEFAULT FALSE,
 generator_market_scheduled bool DEFAULT FALSE,
 generator_market_non_scheduled bool DEFAULT FALSE,
 generator_market_semi_scheduled bool DEFAULT FALSE,
 generator_non_market_scheduled bool DEFAULT FALSE,
 generator_non_market_non_scheduled bool DEFAULT FALSE,
 generator_non_market_semi_scheduled bool DEFAULT FALSE,
 market_small_generation_aggregator bool DEFAULT FALSE,
 market_customer bool DEFAULT FALSE,
 metering_coordinator bool DEFAULT FALSE,
 market_nsp bool DEFAULT FALSE,
 nsp_transmission bool DEFAULT FALSE,
 nsp_distribution bool DEFAULT FALSE,
 nsp_other bool DEFAULT FALSE,
 special_participant_system_operator bool DEFAULT FALSE,
 special_participant_distribution_operator bool DEFAULT FALSE,
 trader bool DEFAULT FALSE,
 intending bool DEFAULT FALSE,
 reallocator bool DEFAULT FALSE
)